version: '{build}'

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe

#configuration:
#  - Debug
#  - Release

before_build:
- cmd: nuget sources add -Name dsp-myget -Source https://www.myget.org/F/dsharpplus-nightly/api/v3/index.json
- cmd: nuget restore

build: off

build_script:
- cmd: dotnet build ModCore.sln -v Minimal -c Release
- cmd: 7z a ModCore.zip "%APPVEYOR_BUILD_FOLDER%\ModCore\bin\Release\netcoreapp2.1\*.dll"
- cmd: 7z a ModCore.zip "%APPVEYOR_BUILD_FOLDER%\Update Scripts\download.ps1"
- cmd: 7z a ModCore.zip "%APPVEYOR_BUILD_FOLDER%\Update Scripts\update.sh"
- cmd: 7z a ModCore.zip "%APPVEYOR_BUILD_FOLDER%\Update Scripts\update.bat"

artifacts:
  - path: ModCore.zip
    name: ModCore Release Build
    
notifications:
  - provider: Slack
    on_build_success: true
    on_build_failure: true
    incoming_webhook:
      secure: 4lwb0Sro3Im5GqSJhMnoQJplQgveO/X4mOqzY11VUZ3CJiP7JUf/h7xU8NWFpOjIkhUdRKHjxeAMQJP0Jv3EUKnaJCM9+NLlnQpozj4UXRJjUnkMSZhp+UuMieCFeyngvbJc/fknnGaqNZtUMskmYJ3GS9h08wQs8IFsiDElqr1C/Uhyx+7HwrGKgIh+9Vgq
